#ifndef THING_PROPERTIES_H
#define THING_PROPERTIES_H

// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "secrets.h"

// uncomment if need callback function for bool isRunning
// void onIsRunningChange();

extern float chipTemp;
extern float nitrateAbs;
extern float nitriteAbs;
extern bool isRunning;

void initProperties();
extern WiFiConnectionHandler ArduinoIoTPreferredConnection;

#endif
